version: 0.0
os: linux
files:
  - source: dist/my-angular-project
    destination: /var/www/my-angular-project
permissions:
  - object: /var/www/my-angular-project
    pattern: '**'
    owner: root
    group: root
    mode: 755
    type: 
      - file
      - directory
  - object: /scripts
    pattern: '**'
    owner: root
    group: root
    mode: 755
    type: 
      - file
      - directory 
hooks:
  BeforeInstall:
    - location: scripts/get-instance-id.sh
      timeout: 300
      runas: root
    - location: scripts/create_directory.sh
      timeout: 300
      runas: root
    - location: scripts/install_Nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
